# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Health' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Health

pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'	
pod 'Firebase/Firestore'	
pod 'Firebase/Storage'

end
